fix: flipper react navigation plugin ui rows text not showing in dark theme (Fix issue #10000)
react-navigation/react-navigation pull request #10001
Opened 2021-09-30 20:01 UTC by react-one

Fix for issue: https://github.com/react-navigation/react-navigation/issues/10000+

In [line 75](https://github.com/react-navigation/react-navigation/blob/main/packages/flipper-plugin-react-navigation/src/Logs.tsx#L75) 

We made the changed to

```tsx
'color': props.selected && '#fff'
```

Because when the color property is not set (falsy value). flipper-plugin by default provide the right colors to the dark and light themes each. ( it get white in dark theme and black in light theme by default in such case ).<br>
So we set it to white only if selected. Otherwise leave it to the default.

In [line 128](https://github.com/react-navigation/react-navigation/blob/main/packages/flipper-plugin-react-navigation/src/Logs.tsx#L128) the color value is always black ('rgba(0, 0, 0, 0.85)'), so in Dark Mode the element "BlankslateText" would be unreadable, so leaving the default element color is the solution.

2021-10-04 00:45 UTC, satya164 requested changes

2021-10-04 00:45 UTC, satya164 commented on packages/flipper-plugin-react-navigation/src/Logs.tsx
> +  'color': props.selected ? '#fff' : '',
I think empty string is weird, it should specify proper color or a keyword (such as `inherit`) to make it clear what it's doing.

However, we need to migrate the plugin to the new architecture to have proper dark theme support if I understand correctly: https://fbflipper.com/docs/extending/sandy-migration/

2021-10-04 00:45 UTC, satya164 commented on packages/flipper-plugin-react-navigation/src/Logs.tsx
> -
Please revert this

2021-10-04 00:45 UTC, satya164 commented on packages/flipper-plugin-react-navigation/src/Logs.tsx
> -
Please revert this

2021-10-04 00:45 UTC, satya164 commented on packages/flipper-plugin-react-navigation/src/Logs.tsx
> -  color: 'rgba(0, 0, 0, 0.85)',
This is to make the text appear lower opacity. If you're removing the color, it needs to add other styling like opacity to keep the same effect.

2021-11-02 14:12 UTC, react-one commented
All notes were taken. 
Closing this PR because i included the fix on PR https://github.com/react-navigation/react-navigation/pull/10004. It's minimal and connected. Having a one PR make sense.

2021-11-02 14:12 UTC, closed without merging