fix: aria-selected should not be set on role link
react-navigation/react-navigation pull request #10019
Opened 2021-10-09 14:07 UTC by vvscode

Covers https://github.com/react-navigation/react-navigation/issues/9418

2021-10-18 09:20 UTC, vvscode commented
@SampsonCrowley FYI

2022-03-15 09:12 UTC, Elter71 commented
Hi, thanks for your contributes. add same changes to packages/bottom-tabs/src/views/BottomTabItem.tsx, on master

2022-03-15 09:23 UTC, Elter71 requested changes

2022-03-15 09:23 UTC, Elter71 commented on packages/drawer/src/__tests__/views/DrawerItem.test.tsx
> +  Platform.OS = 'android';
I think it is not needed. It's working fine without defining OS

2022-11-27 18:37 UTC, closed without merging

2022-11-27 21:31 UTC, satya164 commented
Hello, the PR got closed automatically due to some changes in the main branch. Would you be able to send a new PR? Thank you.