feat(native-stack): export NativeStackView to support custom routers on native-stack
react-navigation/react-navigation pull request #10260
Opened 2022-01-13 13:25 UTC by AdityaPahilwani

Currently, there is no way to create a custom navigator and router on top of **Native-Stack**

So by exporting **NativeStackView** along with its types from native-stack, we can use it along with **useNavigationBuilder** to create custom navigators​ with some additional functionality built on top of it.

We can also use **StackRouter** from **@react-navigation/native** to create customised routers and use it with the navigator we created on top of **NativeStackView**.

We can follow the same doc to extend NativeStackView with our own router or build additional functionality on top of it.
https://reactnavigation.org/docs/custom-navigators#extending-navigators.

2022-01-26 12:30 UTC, satya164 requested changes
Thanks for the PR. I think we don't need to export `NativeStackNavigatorProps` as you can already access it by `React.ComponentProps<typeof NativeStackView>`

Regarding exporting `NativeStackNavigationEventMap`, that's useful but currently, no other navigators export it (afaik). Could you add the export to other navigators as well? Then I'll be happy to merge the PR.

2022-01-26 17:36 UTC, AdityaPahilwani commented
Thanks for the review.
I have added exports for NavigationEventMap from other navigators.

2022-01-27 10:58 UTC, satya164 commented on packages/native-stack/src/index.tsx
> +  NativeStackNavigatorProps,
```suggestion
```

2022-01-27 10:59 UTC, satya164 commented on packages/native-stack/src/index.tsx
> +export { default as NativeStackView } from './views/NativeStackView';
```suggestion

/**
 * Views
 */
 export { default as NativeStackView } from './views/NativeStackView';
```

2022-01-27 11:00 UTC, satya164 approved these changes
Thanks

2022-01-27 11:12 UTC, satya164 commented on packages/native-stack/src/index.tsx
> +
```suggestion
/**
 * Views
 */
export { default as NativeStackView } from './views/NativeStackView';

```

2022-01-27 11:15 UTC, merged