fix : back and forward does not work correctly, items should not have empty indexes
react-navigation/react-navigation pull request #10306
Opened 2022-01-29 01:56 UTC by murataka

In findindexes function , there's no need to

item &&

as the indexes are now being managed properly , I left them just because further testing might be essential and if there's still a mistake in the commit , not to make it crash.

It is possibly safe not to 

`item && `.

2022-01-29 02:46 UTC, murataka commented
Hello, 
let me know if you think this might create any other issue , and any kind of reviews would help. 

I would like to fix any possible issue created by this commit , as much as I can.

Thanks !

2022-01-30 12:21 UTC, murataka commented
These comments were already explaining the below change .

```
       // There are two scenarios for creating an array with only one history record:
        // - When loaded id not found in the items array, this function by default will replace
        //   the first item. We need to keep only the new updated object, otherwise it will break
        //   the page when navigating forward in history.
        // - This is the first time any state modifications are done
        //   So we need to push the entry as there's nothing to replace
```
`items[index] = { path, state, id };` 
to
`items[0] = { path, state, id };`

2022-01-31 17:29 UTC, roryabraham commented on packages/native/src/useLinking.tsx
> +        const index = items.findIndex((item) => item && item.id === id);
```suggestion
        const index = items.findIndex((item) => item?.id === id);
```

2022-01-31 17:29 UTC, roryabraham commented on packages/native/src/useLinking.tsx
> +      if (!items.length || items.findIndex((item) => item && item.id === id) < 0) {
```suggestion
      if (!items.length || items.findIndex((item) => item?.id === id) < 0) {
```

2022-01-31 17:29 UTC, roryabraham commented on packages/native/src/useLinking.tsx
> +          const currentIndex = items.findIndex((item) => item && item.id === id);
```suggestion
          const currentIndex = items.findIndex((item) => item?.id === id);
```

2022-01-31 20:16 UTC, roryabraham approved these changes

2022-02-01 06:35 UTC, satya164 requested changes
This change doesn't make sense to me. The change seems to be that it's always going to replace the first item when calling replace regardless of what the index is which doesn't look correct and going to produce incorrect history.

2022-02-01 08:13 UTC, murataka commented
> This change doesn't make sense to me. The change seems to be that it's always going to replace the first item when calling replace regardless of what the index is which doesn't look correct and going to produce incorrect history.

i shall check if the other solution if still creates empty indexes. feels still there's something missing..

2022-02-01 09:37 UTC, murataka commented
https://github.com/react-navigation/react-navigation/pull/10312

solves the issue , and I did not get any empty indexes while testing it . 

Closing this pull request.

2022-02-01 09:38 UTC, closed without merging