feat: add animation prop to bottom tab
react-navigation/react-navigation pull request #11323
Opened 2023-04-05 12:20 UTC by teneeto

**Description**
----

This PR adds  properties to `bottom-tabs` navigation `screenOptions` to enable animation (as `animationEnabled`),  add custom animations or use presets (as `styleInterpolator`), and also let you set  transition config (as `transitionSpec`) hence, providing a medium to animate bottoms-tabs screens.

**Video Walkthrough**
----
The tabs as shown in the video currently uses a custom `fade` preset.

https://user-images.githubusercontent.com/22779249/230076482-5d5886c3-7f07-4627-a7a0-e0f303ac3047.mov

**Quality check**
----
The change takes into account  lint, typescript and test checks (all passing).

2023-04-19 07:53 UTC, satya164 requested changes
Currently the cross-fade animation is broken. It's more obvious if you slow down the animation. Here I have slowed down the animation by 10x:

https://user-images.githubusercontent.com/1174278/233005257-7b78d7ac-dabd-4af0-9880-4f47d0215aed.mp4

With a cross-fade animation, both of the screens need to stay visible. But currently the unfocused screen always disappears and only the focused screen fades in.

Here's how it should behave:


https://user-images.githubusercontent.com/1174278/233318845-36ca9e1f-bd8b-4b48-ae41-04aefc4d7ac6.mp4



There are 2 reasons for this:

- Inactive screens get detached using `MaybeScreen` and `MaybeScreenContainer`. They need to be kept around for the duration of the animation. This can be achieved by `hasTwoStates={false}` and setting `visible={true}` for the 2 screens which are currently animating.
- The `Screen` component renders `Background` which will render a opaque background hiding the screen underneath. You need to pass `backgroundColor: 'transparent'` and handled the background color to be `colors.background` in the inner view that animates.

2023-04-19 07:53 UTC, satya164 commented on example/src/Screens/BottomTabsAnimated.tsx
> +    </Tab.Navigator>
This navigator can be simplified by removing any customization unrelated to animations (such as blurred tab bar).

2023-04-20 10:33 UTC, teneeto commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +          ...transitionSpec?.config,
Although they are already omitted, i will implement them for safety.

2023-04-20 11:35 UTC, satya164 commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +          ...transitionSpec?.config,
They are only omitted in the types. But it won't prevent users from passing them, especially if they don't use TypeScript.

2023-08-13 08:34 UTC, andreialecu commented
This looks great, and I'm very interested in this feature. 

@teneeto any plans to finish it?

2023-08-14 13:46 UTC, teneeto commented
> This looks great, and I'm very interested in this feature.
> 
> @teneeto any plans to finish it?

Yes, this is in Review. Your contributions would mean a lot too.

2023-08-29 20:06 UTC, osdnk commented
Hi @teneeto, thanks for your contribution and addressing our review. 
Before we can proceed, I need to share one more concern I found out while testing your changes, 
Before: 

https://github.com/react-navigation/react-navigation/assets/25709300/d75de053-cc4c-46d3-9a98-10b9a5f2a6e7
After: 

https://github.com/react-navigation/react-navigation/assets/25709300/a7ca396c-1197-4d12-b7be-4d0368d3aa44

It looks like something is definitely off. That happens only with "regular" bottom tabs. 

Also, we're trying to keep one example per feature, which exhaustively presents all capabilities. Is there a chance we can merge that example into regular bottom-tabs? If yes, we can add a which to turn on/off the preset.

2023-08-29 20:07 UTC, osdnk requested changes
Unfortunately, this is blocking to my understanding.

2023-08-29 21:18 UTC, osdnk commented
@teneeto I think i investigated bugs. Adjusting the example is the remaining part

2023-08-30 12:46 UTC, teneeto commented
> osdnk

Hi Michał, thanks for finding some time to go through this, I'll look into what needs to be improved as soon as I can.

2023-08-30 12:53 UTC, osdnk commented
I only encourage you not to create a new example on the main screen but to integrate it with an existing bottom-tabs example (with a button to turn the animation on and off).

2023-08-31 21:38 UTC, osdnk approved these changes

2023-08-31 21:41 UTC, osdnk commented
I think I'm happy with those changes. I had some issues with flickering with `hasTwoStates` as screens' container. I did a lazy thing and disabled that if any screen has `animationEnabled` (otherwise I faced extra-rerender). It's not changing anything if the we don't use animation.

2023-08-31 21:41 UTC, merged