fix: [Drawer] fix iOS wrong detected frame dimensions
react-navigation/react-navigation pull request #11632
Opened 2023-10-08 12:44 UTC by onmotion

**Motivation**

It seems that under certain scenarios on iOS, the useSafeAreaFrame hook is returning incorrect dimensions. The issue may lie in the native implementation of methods responsible for layout (`layoutSubviews`, `layoutIfNeeded`, etc). However, we only require the `height` and `width` of the main window, as the Drawer is hidden behind the root View and we do not need the x and y coordinates of the top frame as SafeArea `Rect` provides.

**Test plan**

- Open Drawer
- Open iOS Modal
- Rotate screen landscape
- Rotate screen portrait
- Close modal

- [x] The change must pass lint, typescript and tests.

https://github.com/react-navigation/react-navigation/assets/12899080/0145a065-11af-4eb3-9775-6f216546523a

2023-10-31 15:35 UTC, osdnk requested changes
Hi,
Thank you for the PR!

I believe that this should be fixed in the safe-area-context library.
@satya164 had issues with useWindowDimensions returning the wrong value on Samsung phones so I don't think that's the solution.

Also changes the behaviour, e.g. it'll give screen dimensions instead of the dimensions of the frame where the navigation tree is.

2023-11-03 11:17 UTC, onmotion commented
> Hi, Thank you for the PR!
> 
> I believe that this should be fixed in the safe-area-context library. @satya164 had issues with useWindowDimensions returning the wrong value on Samsung phones so I don't think that's the solution.
> 
> Also changes the behaviour, e.g. it'll give screen dimensions instead of the dimensions of the frame where the navigation tree is.

for sure, this should be fixed in in the safe-area-context library, but this issue exist for a years and still there. And I didn't found the case when the Drawer could be behind the frame but not the actual screen.

2024-01-23 17:02 UTC, focux commented
I'm experiencing this same issue and manually patching the drawer with this change fixed it. Thanks @onmotion!

2024-02-13 12:47 UTC, arizoska commented
encountered the same issue, thank you @onmotion! would be great to have this merged

2024-03-14 19:22 UTC, lwhallock commented
I am encountering the same issue and this fix is perfect for my work, thank you @onmotion

2024-06-27 09:46 UTC, satya164 commented
@onmotion can you check if the pr @lwhallock linked fixes this issue?

2024-08-01 06:30 UTC, onmotion commented
> @onmotion can you check if the pr @lwhallock linked fixes this issue?

seems like it's fixed, could be closed I guess

2024-08-01 06:31 UTC, onmotion commented
fixed by https://github.com/th3rdwave/react-native-safe-area-context/pull/480

2024-08-01 06:31 UTC, closed without merging