fix: preserve # in the URL if the screen hasn't changed - partially done
react-navigation/react-navigation pull request #11876
Opened 2024-03-07 14:18 UTC by groot007

**Motivation**

when updating some params on the page, the hash shouldn’t be removed

2024-03-07 16:22 UTC, satya164 requested changes

2024-03-07 16:22 UTC, satya164 commented on packages/native/src/useLinking.tsx
> +      const isSameScreen = path.split('?')[0] === route?.path?.split('?')?.[0];
`path` being the same doesn't always mean it's the same screen. the same screen could have 2 different paths if the params have changed for params in path segment, e.g. `/users/:userId`, 

To know if it's the same screen, you'd need to get the key of the current route (`route.key`) and compare it with the previous key (`route.key`).

2024-03-07 16:58 UTC, satya164 commented
Also let's add some tests as well. You can add them under `example/e2e`.

2024-03-07 19:29 UTC, groot007 commented on packages/native/src/useLinking.tsx
> +      // @ts-expect-error key is ommited for focused route
can not get it why do we have omitted 'key' prop in return type findFocusedRoute - but it present there

2024-03-08 16:32 UTC, satya164 approved these changes

2024-03-08 16:37 UTC, merged