fix: spread key into JSX warning
react-navigation/react-navigation pull request #12142
Opened 2024-09-11 14:38 UTC by jewhyena

**Motivation**

After bumping up versions of `react` from `18.2.0` to `18.3.1` as well as `react-native` from `0.74.5` to `0.75.2` in one of my projects, the application started to give me a warning `A props object containing a "key" prop is being spread into JSX`.

It happens on the screens which use `@react-navigation/material-top-tabs`.

Addresses the existing issue https://github.com/react-navigation/react-navigation/issues/11989.

**Test plan**

1. Initialize a new project with the latest versions of `react` and `react-native`
2. Make use of `@react-navigation/material-top-tabs`
3. See the warning in the console

**Solution**

Passing the key straight to the component instead of spreading it.

I've also removed the `renderTabBarItem` prop since it doesn't seem to be used anywhere and could've caused a more verbose fix. 🤔

2024-09-12 16:47 UTC, satya164 requested changes
> I've also removed the renderTabBarItem prop since it doesn't seem to be used anywhere and could've caused a more verbose fix.

Just because it's not used anywhere in the example in this repo doesn't mean that nobody else is using it. Please don't remove any features in your PR.

It doesn't affect anything in the fix. It's up to the user of that prop to handle the `key` in their own code.

2024-09-18 12:43 UTC, Mibou commented
Hello, would it possible to merge this fix soon please? 😇🙏

2024-09-19 10:00 UTC, dacitto approved these changes

2024-09-24 16:47 UTC, satya164 approved these changes
Thanks!

2024-09-24 16:56 UTC, merged