feat: provide gesture as a render prop to drawer children
react-navigation/react-navigation pull request #12326
Opened 2024-12-07 21:31 UTC by gaearon

Please provide enough information so that others can review your pull request.

**Motivation**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

The drawer gesture can easily conflict with other gestures in the app. In order to coordinate multiple gestures, the app code can use APIs like `requireExternalGestureToFail`. However, since the gesture is hidden in the library, this is not currently possible without patching. This exposes the gesture to the application code so you can use `requireExternalGestureToFail` with it.

```js
<Drawer
  // ...
  >
  {({gesture}) => (
    <MyGestureContext.Provider value={gesture}>
      {/* ... */}
    </MyGestureContext.Provider>
  )}
</Drawer>
```

In components deep down:

```js
const drawerGesture = useContext(MyGestureContext)
const nativeGesture = Gesture.Native()
  .requireExternalGestureToFail(drawerGesture)

// ...

<GestureDetector gesture={nativeGesture}>
  <PagerView
    // ...
  />
</GestureDetector>
```

Note that the existing `configureGestureHandler` is not enough because we need it in the other direction: *other* gestures (deeper in the app) need access to it. It would not be possible to capture it in a closure because by the point `configureGestureHandler` runs, the owner component has already executed and passed the data down. 

**Test plan**

Verify you're able to access `gesture` on mobile. On web, it should be `undefined`.

Verify you can use it with RNGH APIs as usual. For example, https://github.com/bluesky-social/social-app/pull/7007 fixes a longstanding problem with the Bluesky app — the drawer swipe barely worked on iOS. The reason it has been broken for the last two years is because this library did not expose the gesture, and we did not know that it needs to be coordinated.

2024-12-07 21:57 UTC, satya164 requested changes
Thanks for the PR.

I'd prefer to expose it in a context instead, similar to what we do for stack for consistency. In addition, wrapping it in context will make it easy to access it in both the sidebar content as-well-as children, but more importantly it is necessary to access it when using with the drawer navigator since there's no way to pass it in render prop there.

Memoizing seems fine to me. Does it make enough impact to worry about cost?

2024-12-08 03:04 UTC, gaearon commented
Ok, I’ll need to look closer at what it depends on. We just wouldn’t want to send a new value down on every re-render of this component. Since this component is usually at the top, and context search traversal is not free.

2024-12-08 20:08 UTC, gaearon commented
Pushed a context implementation.

2024-12-08 20:10 UTC, gaearon commented on packages/react-native-drawer-layout/src/views/Drawer.native.tsx
> +    if (panGesture && configureGestureHandler) {
It's important for this to be within the useMemo block since it could be mutating.

2024-12-11 09:41 UTC, satya164 approved these changes
Thank you

2024-12-11 09:44 UTC, merged