tabBarBadge accept boolean type
react-navigation/react-navigation pull request #8862
Opened 2020-09-17 09:10 UTC by bruno02100

According to the docs the tabBarBadge accepts a boolean, it works, but the type does not accept it.

2021-02-23 22:17 UTC, ccheney requested changes

2021-02-23 22:17 UTC, ccheney commented on packages/bottom-tabs/src/types.tsx
> +  tabBarBadge?: number | string | boolean;
this should actually be:

`tabBarBadge?: number | string | true;`

Passing in a `false` bool will actually still render the dot

2022-02-01 08:51 UTC, satya164 commented
Thanks for the PR. However, `tabBarBadge` doesn't accept a boolean.

2022-02-01 08:51 UTC, closed without merging

2023-12-05 13:59 UTC, Workshed commented
@satya164 can i clarify this one - I was about to make the same PR. The docs here do indeed suggest that it accepts a boolean (and in testing it does indeed accept a boolean, or at least a `true` value): https://reactnavigation.org/docs/material-bottom-tab-navigator/#tabbarbadge

2023-12-05 14:01 UTC, Workshed commented
How else would you get a badge without a value inside it?