Add an unhandled navigation action listener
react-navigation/react-navigation pull request #8895
Opened 2020-09-23 19:19 UTC by ahmadj-levelbenefits

Often developers miss these console messages: this allows missed routes to be emitted to whatever event logger users prefer.

2020-09-23 19:23 UTC, ahmadj-levelbenefits commented on packages/core/src/__tests__/BaseNavigationContainer.test.tsx
> +  });
Would anyone be able to tell me how to silence the warnings this test emits? The test output is otherwise pristine, and I'd like to preserve that.

2020-10-01 11:06 UTC, satya164 requested changes
Thanks for the PR!

Just 2 small changes:
1. Can you rename `onUnhandledNavigationAction` to `onUnhandledAction`?
2. If a listener is specified, I think we should return instead of showing redbox, since they dev might want to handle it in a different way

2020-10-02 17:40 UTC, ahmadj-levelbenefits commented
Cool - to avoid a name collision prefixed the internal one with `default`.

2020-10-05 12:54 UTC, satya164 commented
Thank you! Looks like the CI is failing due to prettier errors. Can you run `yarn lint --fix` and push the changes so the CI passes?

2020-10-09 14:35 UTC, ahmadj-levelbenefits commented
Ping @satya164

2020-10-09 14:48 UTC, satya164 approved these changes
Thanks!

2020-10-09 14:49 UTC, merged

2020-10-09 14:50 UTC, ahmadj-levelbenefits commented
Thank you!