feat: add sceneContainerStyle prop to bottom-tabs navigator
react-navigation/react-navigation pull request #8947
Opened 2020-10-12 09:19 UTC by wwdrew

This feature adds the sceneContainerStyle prop to the bottom-tabs navigator, to allow setting styles on the container's view. It's already implemented in the material-top-tabs and drawer navigators, I've simply ported it into the bottom-tabs navigator.

It also fixes this issue:

https://github.com/react-navigation/react-navigation/issues/8076

2020-10-22 23:57 UTC, satya164 requested changes

2020-10-22 23:57 UTC, satya164 commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +  sceneContainerStyle?: StyleProp<ViewStyle>;
```suggestion
```

2020-10-22 23:57 UTC, satya164 commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +  sceneContainerStyle,
```suggestion
  style,
```

2020-10-22 23:57 UTC, satya164 commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +  sceneContainerStyle?: StyleProp<ViewStyle>;
```suggestion
  style?: StyleProp<ViewStyle>;
```

2020-10-22 23:57 UTC, satya164 commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +        sceneContainerStyle,
```suggestion
        style,
```

2020-10-22 23:57 UTC, satya164 commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +    sceneContainerStyle: {},
```suggestion
```

2020-10-22 23:57 UTC, satya164 commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +                      sceneContainerStyle={sceneContainerStyle}
```suggestion
                      style={sceneContainerStyle}
```

2020-10-22 23:58 UTC, satya164 commented on example/src/Screens/BottomTabs.tsx
> +      }}
```suggestion
```

2020-10-22 23:59 UTC, satya164 approved these changes
Thanks!

2020-10-23 00:08 UTC, satya164 commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +      ]}
```suggestion
      style={[styles.content, { backgroundColor: colors.background }, style]}
```

2020-10-23 00:16 UTC, merged

2020-10-23 12:50 UTC, mvrdrew commented
Hi @satya164, thanks so much for approving this! Just to let you know, I prepared a PR for the website to document this as well: https://github.com/react-navigation/react-navigation.github.io/pull/877