fix(prefixes): add http or https for default protocol
react-navigation/react-navigation pull request #8968
Opened 2020-10-21 09:51 UTC by hosseinmd

URIs without a scheme are assumed as either http or https. For example, www.google.com matches both http://www.google.com and https://www.google.com.

https://developer.android.com/guide/navigation/navigation-deep-link

2020-10-21 10:17 UTC, satya164 requested changes
Is the behaviour same on both Android and iOS for a default scheme? Unless it is, I'd rather not add any scheme by default. It's easy enough to specify 2 prefixes.

2020-10-21 12:39 UTC, hosseinmd commented
I couldn't find anything about iOS, it seems the iOS schema is required, but our work does not depend on it, we are adding that to have simple prefixes.

2020-10-23 20:37 UTC, hosseinmd commented
With this we have a good doc and don't need to tell developers to add protocol to prefixes

2020-10-23 21:19 UTC, satya164 commented
Thanks, but I believe it's better to be explicit than to implictely assume a scheme which may or may not be correct. It's very little work to add another prefix if you need it.

2020-10-23 21:19 UTC, closed without merging

2020-10-23 23:04 UTC, hosseinmd commented
> Thanks, but I believe it's better to be explicit than to implictely assume a scheme which may or may not be correct. It's very little work to add another prefix if you need it.

That is not about me. Anyway, thank you.