feat: improve useNavigationState typing
react-navigation/react-navigation pull request #9464
Opened 2021-03-26 12:54 UTC by jemmyphan

2021-03-27 19:05 UTC, satya164 requested changes
Thank you for the PR. Can you use `ParamList` instead of `P`? We try to avoid single letter generics for better clarity. We have `T`, but it's for type inference rather than user provided like `ParamList`.

2021-03-28 06:58 UTC, jemmyphan commented
> Thank you for the PR. Can you use `ParamList` instead of `P`? We try to avoid single letter generics for better clarity. We have `T`, but it's for type inference rather than user provided like `ParamList`.

Thanks @satya164 for the review.
I have updated the PR, can you check it again?

2021-03-29 03:41 UTC, satya164 approved these changes

2021-03-29 03:42 UTC, satya164 commented
Thanks

2021-03-29 03:42 UTC, merged