fix: disable screens on windows
react-navigation/react-navigation pull request #9494
Opened 2021-04-12 08:34 UTC by WoLewicki

Added checks for `windows` platform in all navigators since `react-native-screens` does not support it yet.

2021-04-12 08:44 UTC, kacperkapusciak approved these changes

2021-05-09 03:56 UTC, satya164 requested changes

2021-05-09 03:56 UTC, satya164 commented on packages/bottom-tabs/src/views/BottomTabView.tsx
> +    detachInactiveScreens = Platform.OS !== 'windows',
```suggestion
    detachInactiveScreens = Platform.OS === 'web' ||
      Platform.OS === 'android' ||
      Platform.OS === 'ios',
```

2021-05-09 04:39 UTC, satya164 commented
/rebase

2021-05-09 04:42 UTC, satya164 approved these changes

2021-05-09 04:42 UTC, merged