Package: @react-navigation/cli
react-navigation/react-navigation pull request #9974
Opened 2021-09-27 17:18 UTC by react-one

> Based on the argument (e.g. stack), it would check for a package named @react-navigation/stack on npm, and fetch its metadata, or display error if the package doesn't exist

[x] Installing package by name by fetching metadata. And can precise version (ex: stack@6.0.0)
[x] Display error if the package doesn’t exist

> It should use choose which command to use to install based on the following:<br>
> - Use expo if we find expo in the dependencies of package.json<br>
> - Use yarn if the user has yarn.lock file<br>
> - Use npm if the user has package-json.lock<br>
> - If no lockfile is present, use yarn if it's installed, otherwise npm<br>

Implementation:

[x] Pick up the right installer following the logic

- Pick user picked installer if --installer option is provided
- A check and pick expo (expo in package.json)
- If not check yarn.lock (pick yarn)
- If not check package.lock (pick npm)
- If not check if yarn is installed (pick yarn)
- If not pick npm

> It can read the peer dependencies from the metadata and install all packages with one command

[x] Installing peer dependencies read from the metadata.

> For gesture handler, we need to add import 'react-native-gesture-handler'. Right now it's the only package that needs it, so we can hardcode it to check if it was installed, and print a message about adding it, or even add it the top of index.js/index.ts automatically.

[x] Auto-add of import 'react-native-gesture-handler'.<br>
[x] - Check import 'react-native-gesture-handler'. And checking for both index.js|ts and App.js|ts.<br>
[x] - Add it automatically if not already added with a confirmation prompt.<br>
[x] - Auto picks up import quote style from code. If none found default to a single quote.

Done too:

[x] Using loader in cli (ora package) and confirmation prompt (enquirer package)

[x] Implemented logging with levels (with --verbose and --debug cli options too)

[x] Implemented tests for installer pick up. And for react-native-gesture-handle. Used memfs ( in-memory file system ) and fs mocking for tests.

[x] initial doc ( doc file )

## Command line in action

Global preview:

![rnav](https://user-images.githubusercontent.com/90264248/134954521-6d3ffbac-f45b-4e9d-96da-2e9c7a66b2be.gif)

Package doesn't exist:

![rnav_no_package](https://user-images.githubusercontent.com/90264248/134954712-38cce831-c26a-4f05-a130-19aa7d80c6e4.gif)

Precising the installer manually:

![rnav_no_package](https://user-images.githubusercontent.com/90264248/134954805-f3dd6b45-217e-48e3-8dbc-7ffa3dd7d489.gif)

2021-09-30 12:48 UTC, mocktarissa approved these changes

2021-10-04 01:06 UTC, satya164 requested changes
I left some comments, but it's a sizable PR so I haven't completed the review yet.

2021-10-04 01:06 UTC, satya164 commented on packages/cli/src/utils/logger.ts
> +  public setIsVerbose(enable: boolean): this {
Don't use `_` for private properties (it's used in JS as a convention as there's no private properties there), or `public` to match code conventions in the repo.

2021-10-04 01:06 UTC, satya164 commented on packages/cli/package.json
> +    "typescript": "^4.4.3"
We shouldn't duplicate deps such as `typescript` or `jest` here as they are in the root project already. Also `ts-jest` doesn't seem necessary here.

2021-10-15 14:51 UTC, satya164 commented
thanks @react-one. can you post about the ux flow of the cli and features on our discord so others can provide feedback?

2022-05-16 19:16 UTC, react-one commented
- When executing commands using `shell.exec()`. The output wasn't colored. I fixed that by creating a custom exec function based on spawn. I used cross-spawn for cross-platform compatibility.
- And I profited and added colors for our logs.

2022-11-27 18:37 UTC, closed without merging