fix: typings: when merge is true in navigate, allow partial params
react-navigation/react-navigation pull request #9982
Opened 2021-09-29 09:21 UTC by christophehurpeau

Allows to pass only part of parameters when navigate is used with merge: true

2021-11-16 14:29 UTC, LRNZ09 commented
The whole `params` could also be omitted when `merge` is `true`, like:
```javascript
params?: Partial<ParamList[RouteName]>;
```

2021-11-16 14:31 UTC, LRNZ09 requested changes

2021-11-16 14:31 UTC, LRNZ09 commented on packages/core/src/types.tsx
> +          params: Partial<ParamList[RouteName]>;
The whole `params` could also be omitted when `merge` is `true`, like:

```suggestion
          params?: Partial<ParamList[RouteName]>;
```

2022-01-26 12:02 UTC, satya164 commented
Thank you for the PR. However, I can't merge this since this may lead to incorrect typings in certain situations. More details here: https://github.com/react-navigation/react-navigation/pull/9924#issuecomment-930018557

2022-01-26 12:02 UTC, closed without merging

2022-01-27 08:21 UTC, LRNZ09 commented
@satya164 I don't agree, if you say so the `merge` parameter is completely useless since you're going to replace the whole params of the screen anyway.

2022-10-28 12:51 UTC, itsramiel commented
Here comes patch-package again 😪

2022-11-06 02:48 UTC, junkboy0315 commented
This is why we cant move to v6.

The remaining ways are patch packaging or ignoring it in over 100 places.😂😂